language: ruby

cache:
  bundler: true

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.2
  - jruby-9.1.17.0
  - jruby-9.2.6.0
before_script:
  - psql  -c 'create database sequel_bitemporal_test;' -U postgres
env:
  - SQLITE=1 SEQUEL='~> 4.0'
  - SQLITE=1 SEQUEL='~> 5.0'
  - PG=1 SEQUEL='~> 4.0'
  - PG=1 SEQUEL='~> 5.0'
gemfile:
  - ci/sequel.gemfile
matrix:
  allow_failures:
    - rvm: jruby-9.1.17.0
      env: PG=1 SEQUEL='~> 4.0'
    - rvm: jruby-9.1.17.0
      env: PG=1 SEQUEL='~> 5.0'
    - rvm: jruby-9.2.6.0
      env: PG=1 SEQUEL='~> 4.0'
    - rvm: jruby-9.2.6.0
      env: PG=1 SEQUEL='~> 5.0'
