name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: ['**']

jobs:
  tests:
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
    name: Ruby ${{ matrix.ruby }}

    env:
      SEQUEL: "~> 5.0"
      BUNDLE_GEMFILE: "ci/sequel.gemfile"
    steps:
      - uses: actions/checkout@v3
      - name: Install db dependencies and check connections
        run: |
          env PGPASSWORD=postgres psql -h localhost -p ${{ job.services.postgres.ports[5432] }} -U postgres -l
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Create databases
        run: |
          env PGPASSWORD=postgres psql -c 'create database sequel_bitemporal_test;' -U postgres -h localhost -p ${{ job.services.postgres.ports[5432] }}
      - name: Run PostgreSQL tests
        run: bundle exec rake spec
        env:
          TEST_ADAPTER: postgresql
          TEST_DATABASE: sequel_bitemporal_test
          TEST_DATABASE_HOST: localhost
          TEST_DATABASE_PORT: ${{ job.services.postgres.ports[5432] }}
          TEST_USERNAME: postgres
          TEST_PASSWORD: postgres
      - name: Run SQLite tests
        run: bundle exec rake spec
        env:
          TEST_ADAPTER: sqlite
